Repository woowa-techcamp-2021/cashbook-7, pull requests merged in 2021-07, with the labels that each got.

#13 [Feature/#10] 초기 설정 추가
  .gitignore
  client/config/webpack.common.js
  client/config/webpack.development.js
  client/config/webpack.prod.js
  client/index.js
  client/package.json
  client/public/index.html
  client/src/Router.ts
  client/src/index.scss
  client/src/index.ts
  client/src/models/index.ts
  client/src/types.ts
  client/src/utils/handleEvent.ts
  client/src/utils/helper.ts
  client/src/views/calendar/index.ts
  client/src/views/dashboard/index.ts
  client/src/views/header/index.ts
  client/src/views/home/index.ts
  client/tsconfig.json
  client/yarn.lock
Labels: FE, 작업 완료

#12 [Feature/#11] 서버 초기 세팅 & prisma 적용
  .gitignore
  client/config/webpack.common.js
  client/config/webpack.development.js
  client/config/webpack.prod.js
  server/constants/index.ts
  server/database/database.ts
  server/index.js
  server/index.ts
  server/middleware/index.ts
  server/models/schema.prisma
  server/package.json
  server/repository/history.ts
  server/routes/history.ts
  server/routes/index.ts
  server/services/history.ts
  server/tsconfig.json
  server/utils/index.ts
  server/yarn.lock
Labels: BE

#14 [Feature/#1] 공통적으로 사용할 헤더 개발
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
  .gitignore
  client/config/webpack.development.js
  client/src/Router.ts
  client/src/index.scss
  client/src/index.ts
  client/src/static/header.ts
  client/src/static/imageUrls.ts
  client/src/styles/global.scss
  client/src/styles/reset.scss
  client/src/views/account/index.ts
  client/src/views/dashboard/index.ts
  client/src/views/header/index.scss
  client/src/views/header/index.ts
  client/src/views/statistics/index.ts
Labels: FE, 작업 완료

#15 [Feature/#2] 내역페이지 UI 구현
  .gitignore
  client/public/index.html
  client/src/static/constants.ts
  client/src/static/imageUrls.ts
  client/src/styles/global.scss
  client/src/views/account/index.scss
  client/src/views/account/index.ts
  client/src/views/header/index.ts
Labels: FE

#18 [Feature/#2] 컴포넌트 분리 (리팩토링)
  client/src/Router.ts
  client/src/dummyData.ts
  client/src/static/constants.ts
  client/src/utils/helper.ts
  client/src/views/account/index.scss
  client/src/views/account/index.ts
  client/src/views/components/payMethod/payMethod.scss
  client/src/views/components/payMethod/payMethod.ts
  client/src/views/page-components/account/AccountHistory/AccountHistory.scss
  client/src/views/page-components/account/AccountHistory/AccountHistory.ts
  client/src/views/page-components/account/index.scss
  client/src/views/page-components/account/index.ts
  client/src/views/page-components/account/myBalance/myBalance.scss
  client/src/views/page-components/account/myBalance/myBalance.ts
Labels: FE
