Repository woowa-techcamp-2021/cashbook-7, pull requests merged in 2021-08, with the labels that each got.

#19 [Feature/#17] 내역 추가 모달 구현
  client/src/Router.ts
  client/src/models/index.ts
  client/src/static/constants.ts
  client/src/static/imageUrls.ts
  client/src/utils/helper.ts
  client/src/views/components/PayMethods/PayMethods.scss
  client/src/views/components/PayMethods/PayMethods.ts
  client/src/views/components/payMethod/payMethod.ts
  client/src/views/page-components/account/AccountHistory/AccountHistory.scss
  client/src/views/page-components/account/AccountHistory/AccountHistory.ts
  client/src/views/page-components/account/AccountHistoryModal/AccountHistoryModal.scss
  client/src/views/page-components/account/AccountHistoryModal/AccountHistoryModal.ts
  client/src/views/page-components/account/Balance/Balance.scss
  client/src/views/page-components/account/Balance/Balance.ts
  client/src/views/page-components/account/index.scss
  client/src/views/page-components/account/index.ts
  client/src/views/page-components/account/myBalance/myBalance.scss
Labels: FE, 작업 완료

#21 [Feature/#16] 내역 페이지 기능 구현
  client/src/models/api.ts
  client/src/models/index.ts
  client/src/static/image-urls.ts
  client/src/types.ts
  client/src/views/components/Confirm/Confirm.scss
  client/src/views/components/Confirm/Confirm.ts
  client/src/views/components/PayMethods/PayMethods.scss
  client/src/views/components/PayMethods/PayMethods.ts
  client/src/views/components/ResultMessage/ResultMessage.scss
  client/src/views/components/ResultMessage/ResultMessage.ts
  client/src/views/page-components/account-page/AccountHistory/AccountHistory.scss
  client/src/views/page-components/account-page/AccountHistory/AccountHistory.ts
  client/src/views/page-components/account-page/AccountHistoryModal/AccountHistoryModal.scss
  client/src/views/page-components/account-page/AccountHistoryModal/AccountHistoryModal.ts
  client/src/views/page-components/account-page/Balance/Balance.ts
  client/src/views/page-components/account-page/index.ts
Labels: FE, 작업 완료

#25 [Feature/#4] Calendar UI 구현
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
  client/src/Router.ts
  client/src/types.ts
  client/src/views/page-components/calendar-page/Calendar/Calendar.scss
  client/src/views/page-components/calendar-page/Calendar/Calendar.ts
  client/src/views/page-components/calendar-page/index.scss
  client/src/views/page-components/calendar-page/index.ts
Labels: FE, 작업 완료

#27 [Feature/#26] 헤더 수정 및 캘린더에 연동
  client/public/index.html
  client/src/models/index.ts
  client/src/static/constants.ts
  client/src/static/image-urls.ts
  client/src/styles/global.scss
  client/src/types.ts
  client/src/utils/helper.ts
  client/src/views/components/Header/MonthController/MonthController.scss
  client/src/views/components/Header/MonthController/MonthController.ts
  client/src/views/components/Header/index.scss
  client/src/views/components/Header/index.ts
  client/src/views/page-components/calendar-page/Calendar/Calendar.ts
  client/src/views/page-components/calendar-page/index.ts
  client/src/views/page-components/statistics-page/index.scss
Labels: FE, 작업 완료

#30 [feature/#28] DB Schema 설계
  server/models/schema.prisma
Labels: BE, 작업 완료

#33 [Feature/#23] 로그인 페이지 UI
  client/src/Router.ts
  client/src/models/index.ts
  client/src/static/image-urls.ts
  client/src/views/page-components/login-page/index.scss
  client/src/views/page-components/login-page/index.ts
Labels: FE, 작업 완료

#34 [Feature/#9] OAuth 로그인, 자동 로그인, 로그아웃 로직 구현
  client/src/Router.ts
  client/src/index.ts
  client/src/models/api.ts
  client/src/models/index.ts
  client/src/static/constants.ts
  client/src/types.ts
  client/src/utils/helper.ts
  client/src/views/components/Header/index.ts
  server/index.ts
  server/models/schema.prisma
  server/package.json
  server/repository/history.ts
  server/routes/auth.ts
  server/routes/history.ts
  server/routes/index.ts
  server/services/auth.ts
  server/utils/helper.ts
  server/utils/index.ts
  server/yarn.lock
Labels: BE, FE, 작업 완료

#35 [Feature/#32] Payment, Account History API 개발
  client/src/models/index.ts
  client/src/views/page-components/login-page/index.ts
  server/middleware/check-token.ts
  server/middleware/index.ts
  server/models/schema.prisma
  server/routes/account-history.ts
  server/routes/auth.ts
  server/routes/index.ts
  server/routes/pay-method.ts
Labels: BE, 작업 완료

#38 Add logic to include category, payMethod on GET ~/account-history
  server/routes/account-history.ts
Labels: BE

#39 [Feature/#36] api 틀 수정 및 accesstoken 오류 해결
  client/src/models/api.ts
  server/utils/helper.ts
Labels: BE, FE, 작업 중

#40 [Feature/#37] 달력 페이지 API 연동 및 모달 구현
  client/src/index.ts
  client/src/static/constants.ts
  client/src/static/image-urls.ts
  client/src/types.ts
  client/src/utils/helper.ts
  client/src/views/page-components/calendar-page/Calendar/Calendar.scss
  client/src/views/page-components/calendar-page/Calendar/Calendar.ts
  client/src/views/page-components/calendar-page/CalendarModal/CalendarModal.scss
  client/src/views/page-components/calendar-page/CalendarModal/CalendarModal.ts
  client/src/views/page-components/calendar-page/index.ts
Labels: BE, FE, 작업 완료

#42 [Feature/#36] Account 페이지 api 연동
  client/src/dummyData.ts
  client/src/models/api.ts
  client/src/models/index.ts
  client/src/static/constants.ts
  client/src/styles/global.scss
  client/src/types.ts
  client/src/views/components/Header/MonthController/MonthController.scss
  client/src/views/components/Header/index.scss
  client/src/views/components/PayMethods/PayMethods.ts
  client/src/views/page-components/account-page/AccountHistory/AccountHistory.ts
  client/src/views/page-components/account-page/AccountHistoryModal/AccountHistoryModal.ts
  client/src/views/page-components/account-page/index.scss
  client/src/views/page-components/account-page/index.ts
  client/src/views/page-components/calendar-page/Calendar/Calendar.scss
  client/src/views/page-components/calendar-page/index.ts
  server/routes/account-history.ts
  server/routes/auth.ts
Labels: FE, 작업 완료

#43 [Feature/#41] 통계 페이지 API 연동
  client/src/types.ts
  client/src/views/page-components/statistics-page/ExpenseByAllCategory/ExpenseByAllCategory.scss
  client/src/views/page-components/statistics-page/ExpenseByAllCategory/ExpenseByAllCategory.ts
  client/src/views/page-components/statistics-page/ExpenseBySpecificCategory/ExpenseBySpecificCategory.scss
  client/src/views/page-components/statistics-page/ExpenseBySpecificCategory/ExpenseBySpecificCategory.ts
  client/src/views/page-components/statistics-page/RecentlyAccountHistory/RecentlyAccountHistory.scss
  client/src/views/page-components/statistics-page/RecentlyAccountHistory/RecentlyAccountHistory.ts
  client/src/views/page-components/statistics-page/index.ts
  server/constants/index.ts
  server/repository/history.ts
  server/routes/category.ts
  server/routes/index.ts
  server/utils/helper.ts
Labels: FE, BE, 작업 완료

#46 [feature/#44] 홈 화면 스타일 개선
  client/src/static/image-urls.ts
  client/src/styles/global.scss
  client/src/views/page-components/login-page/index.scss
  client/src/views/page-components/login-page/index.ts
Labels: FE, BE, 작업 완료

#47 [Feature/#45] 내역페이지 UI 최종 수정
  client/src/views/components/PayMethods/PayMethods.scss
  client/src/views/components/PayMethods/PayMethods.ts
  client/src/views/page-components/account-page/AccountHistory/AccountHistory.scss
  client/src/views/page-components/account-page/AccountHistory/AccountHistory.ts
  client/src/views/page-components/account-page/AccountHistoryModal/AccountHistoryModal.scss
  client/src/views/page-components/account-page/AccountHistoryModal/AccountHistoryModal.ts
  client/src/views/page-components/account-page/Balance/Balance.scss
  client/src/views/page-components/account-page/index.ts
Labels: FE, 작업 완료
